baseURL = "https://thunderbottom.github.io"
languageCode = "en-us"
title = "Chinmay Pai"
theme = "coder"

paginate = 20
canonifyurls = false

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    pagetitle = "chinmaypai"
    author = "Chinmay D. Pai"
    info = "hm, i am unsure"
    description = "i dont know?"
    keywords = "blog,developer,personal"

    hideCredits = true
    hideCopyright = true
    

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/thunderbottom"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/pacmansyyu"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/chinmaydpai/"
[[params.social]]
    name = "Keybase"
    weight = 4
    url = "https://keybase.io/chinmaypai"



[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "GPG"
    weight = 2
    url = "/gpg/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
